"""GENERATED by tools/make_wyrm_spans.py — do not edit.

The hearth-wyrm silhouette as (x, y, w, h) rectangles in mm, origin at the
bottom-left of the canvas. BODY + NECK + POSED HEAD, exactly as the device
composites them -- see silhouette() for the two bugs that made this a
two-piece mark with no neck.
bottom-left of the grille field. Traced from esphome/art/dragon.py, the same
curves the device and the website draw.
"""

# 104 rects, 193.4 mm2, dilated 2px, canvas 120x50px at 0.3083 mm/px.
WYRM_W, WYRM_H = 37.0000, 15.4167
WYRM_AREA = 193.3503
# MIN FEATURE. TWO NUMBERS, BECAUSE THEY ARE NOT THE SAME THING AND THE
# DIFFERENCE USED TO BE HIDDEN.
#
# WYRM_MIN_FEATURE is the CONSUMER CONTRACT and a conservative LOWER BOUND:
# scale this silhouette by (your print floor / this) and every feature comes
# out at or above your floor. It is 4*px = four pixels of the canvas, so it
# is a statement about the GRID, not a measurement of the shape -- which is
# why it errs safe. Erring safe is the whole reason it is still here.
#
# WYRM_MIN_FEATURE_MEASURED is the shape's ACTUAL thinnest feature, by
# Euclidean-disc opening with the thickness read off the distance transform
# (tools/minfeature.py, whose control runs on every regeneration). The build
# asserts MEASURED >= WYRM_MIN_FEATURE, i.e. that the bound IS a bound -- a
# check nobody had ever run.
#
# THE GAP MATTERS TO CONSUMERS: it is 2.00x, so a
# consumer scaling by floor/1.2333 gets a mark whose thinnest
# feature is 2.00x its floor, NOT equal to it. Anything
# that reports `WYRM_MIN_FEATURE * s` as the result is ARITHMETIC, NOT A
# TEST -- it returns the floor by construction whatever the shape does.
# Use MEASURED * s for that.
#
# AND THE FLOOR BOUNDS THE SCALE FROM BELOW, NOT ABOVE: scaling up multiplies
# every feature by s, so a LARGER mark is strictly safer to print. Any claim
# that a mark is 'as large as the print floor allows' has the sign wrong.
WYRM_MIN_FEATURE = 1.2333
WYRM_MIN_FEATURE_MEASURED = 2.4667   # EDT ridge minimum, at
# canvas (14.18, 26.21) in the mask's own axis order.
# Granulometric lower bound at tol=0.005, for comparison: 0.8721
# The old 4-connected metric, kept only for comparison: it reported the loss
# at k=2 as 0.0%. It is anisotropic -- see minfeature.py.
# CONNECTED COMPONENTS of the silhouette. 1 means the mark is NOT one
# piece: body_mask()|head_mask(0) unions two sprites and the k=0 head pose
# leaves the neck clear of the body. On screen the fire fills the gap; in
# plastic nothing does. A gap is not a thin feature, so no minimum-feature
# test can see it.
WYRM_COMPONENTS = 1
WYRM_COMPONENT_GAP = 0.0000   # mm, largest two components
WYRM = [
    (34.5333, 15.1083, 0.3083, 0.3083),
    (34.225, 14.8, 0.925, 0.3083),
    (33.9167, 14.4917, 1.5417, 0.3083),
    (33.9167, 14.1833, 1.85, 0.3083),
    (33.9167, 13.875, 1.85, 0.3083),
    (33.6083, 13.5667, 2.1583, 0.3083),
    (33.3, 13.2583, 2.4667, 0.3083),
    (32.9917, 12.95, 2.775, 0.3083),
    (32.9917, 12.6417, 2.775, 0.3083),
    (32.9917, 12.3333, 2.775, 0.3083),
    (32.0667, 12.025, 0.3083, 0.3083),
    (33.3, 12.025, 2.4667, 0.3083),
    (31.7583, 11.7167, 0.925, 0.3083),
    (32.9917, 11.7167, 2.775, 0.3083),
    (31.45, 11.4083, 4.0083, 0.3083),
    (31.45, 11.1, 4.0083, 0.3083),
    (31.45, 10.7917, 4.0083, 0.3083),
    (29.9083, 10.4833, 0.3083, 0.3083),
    (31.45, 10.4833, 3.7, 0.3083),
    (29.6, 10.175, 0.925, 0.3083),
    (30.8333, 10.175, 4.0083, 0.3083),
    (9.25, 9.8667, 0.3083, 0.3083),
    (29.2917, 9.8667, 5.55, 0.3083),
    (8.9417, 9.5583, 0.925, 0.3083),
    (29.2917, 9.5583, 5.2417, 0.3083),
    (8.6333, 9.25, 1.5417, 0.3083),
    (11.7167, 9.25, 0.3083, 0.3083),
    (27.4417, 9.25, 0.6167, 0.3083),
    (28.9833, 9.25, 5.2417, 0.3083),
    (7.4, 8.9417, 2.775, 0.3083),
    (11.4083, 8.9417, 0.925, 0.3083),
    (27.1333, 8.9417, 1.2333, 0.3083),
    (28.675, 8.9417, 5.2417, 0.3083),
    (7.0917, 8.6333, 3.3917, 0.3083),
    (11.1, 8.6333, 1.5417, 0.3083),
    (26.825, 8.6333, 6.7833, 0.3083),
    (6.7833, 8.325, 3.7, 0.3083),
    (10.7917, 8.325, 1.85, 0.3083),
    (24.975, 8.325, 0.3083, 0.3083),
    (26.825, 8.325, 6.475, 0.3083),
    (6.475, 8.0167, 4.0083, 0.3083),
    (10.7917, 8.0167, 1.85, 0.3083),
    (14.1833, 8.0167, 0.3083, 0.3083),
    (24.6667, 8.0167, 0.925, 0.3083),
    (26.2083, 8.0167, 6.7833, 0.3083),
    (6.475, 7.7083, 6.1667, 0.3083),
    (13.875, 7.7083, 0.925, 0.3083),
    (22.2, 7.7083, 0.3083, 0.3083),
    (24.3583, 7.7083, 8.325, 0.3083),
    (6.1667, 7.4, 6.7833, 0.3083),
    (13.5667, 7.4, 1.5417, 0.3083),
    (16.65, 7.4, 0.3083, 0.3083),
    (19.425, 7.4, 0.3083, 0.3083),
    (21.8917, 7.4, 0.925, 0.3083),
    (24.3583, 7.4, 8.0167, 0.3083),
    (6.1667, 7.0917, 6.7833, 0.3083),
    (13.2583, 7.0917, 1.85, 0.3083),
    (16.3417, 7.0917, 0.925, 0.3083),
    (19.1167, 7.0917, 0.925, 0.3083),
    (21.5833, 7.0917, 10.4833, 0.3083),
    (6.1667, 6.7833, 8.9417, 0.3083),
    (16.0333, 6.7833, 1.5417, 0.3083),
    (18.8083, 6.7833, 1.5417, 0.3083),
    (21.5833, 6.7833, 10.175, 0.3083),
    (6.475, 6.475, 11.4083, 0.3083),
    (18.8083, 6.475, 12.6417, 0.3083),
    (6.1667, 6.1667, 24.975, 0.3083),
    (6.1667, 5.8583, 24.6667, 0.3083),
    (4.3167, 5.55, 0.925, 0.3083),
    (5.8583, 5.55, 24.3583, 0.3083),
    (3.7, 5.2417, 26.2083, 0.3083),
    (2.775, 4.9333, 26.5167, 0.3083),
    (2.1583, 4.625, 26.825, 0.3083),
    (1.5417, 4.3167, 27.1333, 0.3083),
    (1.2333, 4.0083, 27.4417, 0.3083),
    (0.925, 3.7, 28.0583, 0.3083),
    (0.6167, 3.3917, 9.25, 0.3083),
    (10.175, 3.3917, 18.8083, 0.3083),
    (0.6167, 3.0833, 8.9417, 0.3083),
    (11.1, 3.0833, 14.1833, 0.3083),
    (25.5917, 3.0833, 3.7, 0.3083),
    (0.6167, 2.775, 8.9417, 0.3083),
    (12.3333, 2.775, 11.7167, 0.3083),
    (26.2083, 2.775, 3.0833, 0.3083),
    (0.925, 2.4667, 8.6333, 0.3083),
    (13.875, 2.4667, 8.325, 0.3083),
    (26.5167, 2.4667, 2.775, 0.3083),
    (1.2333, 2.1583, 8.0167, 0.3083),
    (16.0333, 2.1583, 3.7, 0.3083),
    (26.5167, 2.1583, 2.775, 0.3083),
    (2.1583, 1.85, 7.0917, 0.3083),
    (25.5917, 1.85, 3.7, 0.3083),
    (3.3917, 1.5417, 6.1667, 0.3083),
    (25.2833, 1.5417, 4.0083, 0.3083),
    (5.2417, 1.2333, 4.625, 0.3083),
    (24.975, 1.2333, 4.625, 0.3083),
    (5.2417, 0.925, 4.625, 0.3083),
    (24.975, 0.925, 4.625, 0.3083),
    (5.2417, 0.6167, 4.3167, 0.3083),
    (24.975, 0.6167, 4.3167, 0.3083),
    (5.55, 0.3083, 3.7, 0.3083),
    (25.2833, 0.3083, 3.7, 0.3083),
    (5.8583, 0.0, 3.0833, 0.3083),
    (25.5917, 0.0, 3.0833, 0.3083),
]
